name: "Auto-Post Milestone Updates"

on:
  issues:
    types: [closed]  # Trigger when a student closes an issue (task completion)

permissions:
  issues: write
  discussions: write

jobs:
  post-milestone-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug GitHub CLI Version and Available Commands
        run: |
          gh --version
          gh help

      - name: Install GitHub CLI Extension for Discussions (If Needed)
        run: |
          gh extension install github/gh-discussions
          gh extension list

      - name: Debug Extensions
        run: |
          gh extension list
          gh help discussion

      - name: Post Update to Discussion in StudentResearch
        run: |
          gh discussion comment create 1 --body "✅ **Milestone Completed in [${{ github.repository }}]**: ${{ github.event.issue.title }} - [View Details](https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
