name: "Auto-Post Milestone Updates"
on:
  issues:
    types: [closed]

jobs:
  post-milestone-update:
    runs-on: ubuntu-latest
    steps:
      - name: Post Update to Discussion
        run: |
          gh discussion comment create 1 --body "✅ **Milestone Completed in [${{ github.repository }}]**: ${{ github.event.issue.title }} - [View Details](https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
